import { ArrowRight, BarChart3, Bot, CheckCircle2, FlaskConical, ShieldCheck, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import Brand from '../components/Brand'

const features = [
  { icon: FlaskConical, title: 'Lab-aware prediction', text: 'Turn routine laboratory markers and symptoms into an interpretable outbreak risk estimate.' },
  { icon: BarChart3, title: 'Population analytics', text: 'Follow risk distribution, disease categories, and probability trends from one dashboard.' },
  { icon: Bot, title: 'Safe consultation', text: 'Offer general health guidance with explicit disclaimers and emergency symptom escalation.' },
]

export default function Landing() {
  return (
    <div className="min-h-screen overflow-hidden bg-[#f5fbfa]">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Brand /><div className="hidden items-center gap-8 text-sm font-semibold md:flex"><a href="#platform">Platform</a><a href="#safety">Safety</a><a href="#about">About</a></div><Link className="btn-primary !px-4 !py-2.5" to="/dashboard">Open platform <ArrowRight size={17} /></Link></nav>
      <main>
        <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-2 lg:py-24">
          <div className="absolute -right-40 top-0 h-96 w-96 rounded-full bg-teal-200/40 blur-3xl" />
          <div className="relative"><span className="inline-flex items-center gap-2 rounded-full border border-teal-200 bg-white px-3 py-1.5 text-xs font-bold text-teal-700"><Sparkles size={14} /> AI FOR PUBLIC HEALTH</span><h1 className="mt-6 text-4xl font-extrabold leading-tight text-ink sm:text-5xl lg:text-6xl">See health risk<br /><span className="text-teal-600">before it spreads.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">OutbreakAI combines laboratory data, symptoms, and machine learning to support faster, clearer community health monitoring.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" to="/predict">Run a prediction <ArrowRight size={18} /></Link><Link className="btn-secondary" to="/dashboard">View live dashboard</Link></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-600"><span className="flex items-center gap-2"><CheckCircle2 className="text-teal-600" size={17} /> Privacy minded</span><span className="flex items-center gap-2"><CheckCircle2 className="text-teal-600" size={17} /> Explainable output</span><span className="flex items-center gap-2"><CheckCircle2 className="text-teal-600" size={17} /> Free to deploy</span></div></div>
          <div className="relative"><div className="card relative overflow-hidden p-5 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><p className="text-sm text-slate-500">Community overview</p><h3 className="mt-1 text-xl font-bold">Surveillance snapshot</h3></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">● Live model</span></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-teal-600 p-5 text-white"><p className="text-xs text-teal-100">Outbreak probability</p><p className="mt-3 text-4xl font-bold">67%</p><div className="mt-4 h-1.5 rounded-full bg-white/20"><div className="h-full w-2/3 rounded-full bg-white" /></div></div><div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs text-slate-500">Current risk</p><p className="mt-3 text-2xl font-bold text-amber-500">Medium</p><p className="mt-3 text-xs text-slate-500">Monitor closely</p></div></div><div className="mt-4 rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between"><p className="text-sm font-bold">Weekly signal</p><p className="text-xs text-teal-600">+12.4%</p></div><div className="mt-5 flex h-28 items-end gap-2">{[28,40,35,55,48,72,64,80,76,92].map((height, index) => <div key={index} className="flex-1 rounded-t bg-teal-100" style={{ height: `${height}%` }}><div className="h-2 rounded-t bg-teal-500" /></div>)}</div></div></div><div className="absolute -bottom-5 -left-5 hidden rounded-2xl bg-white p-4 shadow-xl sm:flex sm:items-center sm:gap-3"><span className="rounded-xl bg-emerald-50 p-2 text-emerald-600"><ShieldCheck /></span><div><p className="text-sm font-bold">Safety first</p><p className="text-xs text-slate-500">Emergency-aware guidance</p></div></div></div>
        </section>
        <section id="platform" className="bg-white py-20"><div className="mx-auto max-w-7xl px-5"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-600">One connected platform</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">From a lab result to a clearer response</h2><p className="mt-4 leading-7 text-slate-500">Designed for students, researchers, clinics, and public-health teams exploring responsible predictive surveillance.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:border-teal-300 hover:shadow-soft"><span className="inline-grid rounded-xl bg-teal-50 p-3 text-teal-700"><Icon /></span><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>)}</div></div></section>
        <section id="safety" className="bg-[#0b2b2e] py-16 text-white"><div className="mx-auto flex max-w-5xl flex-col items-center px-5 text-center"><ShieldCheck size={36} className="text-teal-400" /><h2 className="mt-4 text-3xl font-bold">Built with the right boundaries</h2><p className="mt-4 max-w-2xl leading-7 text-slate-300">OutbreakAI supports—not replaces—professional judgment. Predictions are estimates, chatbot guidance is general, and emergency symptoms always trigger urgent-care instructions.</p></div></section>
      </main>
      <footer id="about" className="border-t border-slate-200 bg-white py-7"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 px-5 text-sm text-slate-500 sm:flex-row"><p>© 2026 OutbreakAI. Academic decision-support project.</p><p>Not for clinical diagnosis.</p></div></footer>
    </div>
  )
}

